# Extensions
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.arithmatex:
    generic: true
- footnotes
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      name: mermaid
      format: !!python/name:mermaid2.fence_mermaid_custom
- pymdownx.mark
- pymdownx.tabbed:
      alternate_style: true
- attr_list
- pymdownx.emoji: null
- def_list
- pymdownx.tasklist:
    custom_checkbox: true
- tables
# Navigation
nav:
- Home:
  - About: index.md
- ADW_STAGE:
  - Stage Layer: adw_stage/mapping_spec_template.md
- ADW_RDV:
  - HUB:
    - Hub Objects: adw_rdv/mapping_spec_template.md
  - LINK:
    - Link Objects: adw_rdv/mapping_spec_template.md
  - SAT:
    - Sat Objects: adw_rdv/mapping_spec_template.md
    - RDV Example: adw_rdv/rdv_example.md
- ADW_BDV:
  - BDV Objects: adw_bdv/mapping_spec_template.md
  - BDV Example: adw_bdv/bdv_example.md
  - BDV Example With Table Link: adw_bdv/bdv_example_with_table_link.md
  - BDV Example Without Table: adw_bdv/bdv_example_without_table.md
  - Feedback CSAT Survey Rep: adw_bdv/FDBK_CSAT_SURVEY_REP.md
  - Feedback CSAT Survey Rep DDL Version: adw_bdv/FDBK_CSAT_SURVEY_REP_ddl_edit.md
  - Test 1: adw_bdv/bdv_example copy 2.md
  - Test 2: adw_bdv/bdv_example copy 3.md
  - Test 3: adw_bdv/bdv_example copy 4.md
  - Test 4: adw_bdv/bdv_example copy 5.md
  - Test 5: adw_bdv/bdv_example copy 6.md
  - Test 6: adw_bdv/bdv_example copy 7.md
  - Test 7: adw_bdv/bdv_example copy 8.md
  - Test 8: adw_bdv/bdv_example copy 9.md
  - Test 9: adw_bdv/bdv_example copy 10.md
  - Test 10: adw_bdv/bdv_example copy 11.md
  - Test 11: adw_bdv/bdv_example copy 12.md
  - Test 12: adw_bdv/bdv_example copy 13.md
  - Test 13: adw_bdv/bdv_example copy 14.md
  - Test 14: adw_bdv/bdv_example copy 15.md
  - Test 15: adw_bdv/bdv_example copy 16.md
  - Test 16: adw_bdv/bdv_example copy 17.md
  - Test 17: adw_bdv/bdv_example copy 18.md
  - Test 18: adw_bdv/bdv_example copy 19.md
  - Test 19: adw_bdv/bdv_example copy 20.md
  - Test 20: adw_bdv/bdv_example copy 21.md
  - Test 21: adw_bdv/bdv_example copy 22.md
  - Test 22: adw_bdv/bdv_example copy 23.md
  - Test 23: adw_bdv/bdv_example copy 24.md
  - Test 24: adw_bdv/bdv_example copy 25.md
  - Test 25: adw_bdv/bdv_example copy 26.md
  - Test 26: adw_bdv/bdv_example copy 27.md
  - Test 27: adw_bdv/bdv_example copy 28.md
  - Test 28: adw_bdv/bdv_example copy 29.md
  - Test 29: adw_bdv/bdv_example copy 30.md
  - Test 30: adw_bdv/bdv_example copy 31.md
  - Test 31: adw_bdv/bdv_example copy 32.md
  - Test 32: adw_bdv/bdv_example copy 33.md
  - Test 33: adw_bdv/bdv_example copy 34.md
  - Test 34: adw_bdv/bdv_example copy 35.md
  - Test 35: adw_bdv/bdv_example copy 36.md
  - Test 36: adw_bdv/bdv_example copy 37.md
  - Test 37: adw_bdv/bdv_example copy 38.md
  - Test 38: adw_bdv/bdv_example copy 40.md
  - Test 39: adw_bdv/bdv_example copy 41.md
  - Test 40: adw_bdv/bdv_example copy 42.md
  - Test 41: adw_bdv/bdv_example copy 43.md
  - Test 42: adw_bdv/bdv_example copy 44.md
  - Test 43: adw_bdv/bdv_example copy 45.md
  - Test 44: adw_bdv/bdv_example copy 46.md
  - Test 45: adw_bdv/bdv_example copy 47.md
  - Test 46: adw_bdv/bdv_example copy 48.md
  - Test 47: adw_bdv/bdv_example copy 49.md
  - Test 48: adw_bdv/bdv_example copy 50.md
  - Test 49: adw_bdv/bdv_example copy 39.md 
- ADW_INSERT_SCHEMA_PL:
  - FACT:
    - Fact Objects: adw_pl/mapping_spec_template.md
    - PL Example: adw_pl/pl_example.md
  - DIMENSION:
    - Dim Objects: adw_pl/mapping_spec_template.md
# Plugins
plugins:
- search
- markdown-filter
- table-reader
- git-revision-date-localized
- git-authors
- mermaid2:
    version: 10.0.2
repo_name: Insert Data Product Repo Name Here
repo_url: https://github.com/sainsburys-tech/
site_name: Insert Data Product Name here
site_url: https://mappingspecexample.com/
# Theme
theme:
  name: material
  custom_dir: 'docs/css'
  features:
  - instant.page_filter: true
  - instant.page_search: true
  - instant.navigation.expand: true
  - instant.navigation.tabs: true
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  - navigation.expand
  - navigation.path
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  - navigation.tracking
  font:
    text: Mary Ann
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
  - accent: green
    primary: blue grey
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - accent: green
    primary: blue grey
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  static_templates:
    - '404.html'
extra_css:
  - 'css/custom.css'
  - 'https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css'
extra_javascript:
  - 'https://unpkg.com/mermaid@10.0.2/dist/mermaid.min.js'
  - 'https://code.jquery.com/jquery-3.5.1.min.js'
  - 'https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js'
  - 'js/extra.js'
