# Site Details
site_name: dp-c3fn-packaging
site_url: https://mappingspecexample.com/
# Site Navigation
nav:
  - Home: 
    - About: "index.md"
    - Installation Instructions: "README.md"
  - Staging:
    - test: Staging/test.md
  - Raw Data Vault:
    - Hubs: 
      - Hub Test 1: Raw Data Vault/hub.md
      - Hub Test 2: Raw Data Vault/test.md
    - Satellites: 
      - Sat Test 1: Raw Data Vault/test.md
    - Links: 
      - Link Test 1: Raw Data Vault/test.md
  - Business Data Vault: 
    - Item Specification Component BR: Business Data Vault/ITEM_SPECIFICATION_COMPONENT_BR.md
  - Presentation Layer:
    - Facts:
      - Agg Item Primary Plastics: Presentation Layer/AGG_ITEM_PRIMARY_PLASTICS.md
      - Fact Item Specification Component: Presentation Layer/FACT_ITEM_SPECIFICATION_COMPONENT.md
    - Dimensions:
      - Dim Test 1: Presentation Layer/test.md
# Theme Details      
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.expand
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.tracking
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep orange
      accent: green
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep orange
      accent: green
  icon:
    repo: fontawesome/brands/github
# Font    
  font:
    text: Mary Ann
# Markdown Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
# Github Links 
repo_name: dp-c3fn-packaging
repo_url: https://github.com/sainsburys-tech/dp-c3fn-packaging/tree/PFBP-290
# Document Plugins
plugins:
  - search
  - markdown-filter
  - table-reader